  sourceDirectory: 'plugins'
  destinationRepo: 'flatfilers/guides'
  destinationDirectory: 'plugins'
  packages:
    - name: '@flatfile/plugin-autocast'
      dir: 'autocast'
      type: 'transform'
    - name: '@flatfile/plugin-automap'
      dir: 'automap'
      type: 'automations'
    - name: '@flatfile/plugin-constraints'
      dir: 'constraints'
      type: 'core_plugin'
    - name: '@flatfile/plugin-dedupe'
      dir: 'dedupe'
      type: 'transform'
    - name: '@flatfile/plugin-delimiter-extractor'
      dir: 'delimiter-extractor'
      type: 'extractors'
    - name: '@flatfile/plugin-export-workbook'
      dir: 'export-workbook'
      type: 'automations'
    - name: '@flatfile/plugin-foreign-db-extractor'
      dir: 'foreign-db-extractor'
      type: 'extractors'
    - name: '@flatfile/plugin-graphql-schema'
      dir: 'graphql-schema'
      type: 'transform'
    - name: '@flatfile/plugin-job-handler'
      dir: 'job-handler'
      type: 'extractors'
    - name: '@flatfile/plugin-json-extractor'
      dir: 'json-extractor'
      type: 'extractors'
    - name: '@flatfile/plugin-convert-json-schema'
      dir: 'json-schema'
      type: 'schema'
    - name: '@flatfile/plugin-convert-openapi-schema'
      dir: 'openapi-schema'
      type: 'schema'
    - name: '@flatfile/plugin-pdf-extractor'
      dir: 'pdf-extractor'
      type: 'extractors'
    - name: '@flatfile/plugin-record-hook'
      dir: 'record-hook'
      type: 'transform'
    - name: '@flatfile/plugin-space-configure'
      dir: 'space-configure'
      type: 'core_plugin'
    - name: '@flatfile/plugin-convert-sql-ddl'
      dir: 'sql-ddl-converter'
      type: 'schema'
    - name: '@flatfile/plugin-webhook-egress'
      dir: 'webhook-egress'
      type: 'automations'
    - name: '@flatfile/plugin-xlsx-extractor'
      dir: 'xlsx-extractor'
      type: 'extractors'
    - name: '@flatfile/plugin-xml-extractor'
      dir: 'xml-extractor'
      type: 'extractors'
    - name: '@flatfile/plugin-convert-yaml-schema'
      dir: 'yaml-schema'
      type: 'schema'
    - name: '@flatfile/plugin-zip-extractor'
      dir: 'zip-extractor'
      type: 'extractors'
