export const MERGE_ACCESS_KEY = 'MERGE_ACCESS_KEY'
export const MAX_SYNC_ATTEMPTS = 30 // Thirty cycles is equates to approx. 5 minutes
export const SYNC_RETRY_INTERVAL_MS = 10000 // 10 seconds
// TODO: add common models to all categories
export const CATEGORY_MODELS = {
  // accounting: {
  //   Account: 'accounts',
  //   Address: 'addresses',
  //   Attachment: 'attachments',
  //   BalanceSheet: 'balanceSheets',
  //   CashFlowStatement: 'cashFlowStatements',
  //   CompanyInfo: 'companyInfo',
  //   CreditNote: 'creditNotes',
  //   Expense: 'expenses',
  //   IncomeStatement: 'incomeStatements',
  //   Invoice: 'invoices',
  //   Item: 'items',
  //   JournalEntry: 'journalEntries',
  //   Payment: 'payments',
  //   PhoneNumber: 'phoneNumbers',
  //   PurchaseOrder: 'purchaseOrders',
  //   TaxRate: 'taxRates',
  //   TrackingCategory: 'trackingCategories',
  //   Transaction: 'transactions',
  //   VendorCredit: 'vendorCredits',
  // },
  // ats: {},
  // crm: {},
  // filestorage: {},
  hris: {
    BankInfo: 'bankInfo',
    Benefit: 'benefits',
    Company: 'companies',
    Dependent: 'dependents',
    EmployeePayrollRun: 'employeePayrollRuns',
    Employee: 'employees',
    EmployerBenefit: 'employerBenefits',
    Employment: 'employments',
    Group: 'groups',
    Location: 'locations',
    PayGroup: 'payGroups',
    PayrollRun: 'payrollRuns',
    TimeOff: 'timeOff',
    TimeOffBalance: 'timeOffBalances',
  },
  // ticketing: {
  //   Ticket: "tickets",
  //   Comment: "comments",
  //   Attachment: "attachments",
  //   Collection: "collections",
  //   Issue: "issues",
  //   Project: "projects",
  //   Team: "teams",
  //   User: "users",
  //   Tag: "tags",
  // },
}
