import { Flatfile } from '@flatfile/api'

export const cashFlowStatements: Flatfile.SheetConfig = {
  name: 'Cash Flow Statements',
  slug: 'cashFlowStatements',
  fields: [
    {
      key: 'id',
      label: 'ID',
      type: 'string',
      constraints: [{ type: 'required' }],
    },
    {
      key: 'remote_id',
      label: 'Remote ID',
      type: 'string',
    },
    {
      key: 'name',
      label: 'Name',
      type: 'string',
    },
    {
      key: 'currency',
      label: 'Currency',
      type: 'enum',
      config: {
        options: [
          { value: 'XUA' },
          { value: 'AFN' },
          { value: 'AFA' },
          { value: 'ALL' },
          { value: 'ALK' },
          { value: 'DZD' },
          { value: 'ADP' },
          { value: 'AOA' },
          { value: 'AOK' },
          { value: 'AON' },
          { value: 'AOR' },
          { value: 'ARA' },
          { value: 'ARS' },
          { value: 'ARM' },
          { value: 'ARP' },
          { value: 'ARL' },
          { value: 'AMD' },
          { value: 'AWG' },
          { value: 'AUD' },
          { value: 'ATS' },
          { value: 'AZN' },
          { value: 'AZM' },
          { value: 'BSD' },
          { value: 'BHD' },
          { value: 'BDT' },
          { value: 'BBD' },
          { value: 'BYN' },
          { value: 'BYB' },
          { value: 'BYR' },
          { value: 'BEF' },
          { value: 'BEC' },
          { value: 'BEL' },
          { value: 'BZD' },
          { value: 'BMD' },
          { value: 'BTN' },
          { value: 'BOB' },
          { value: 'BOL' },
          { value: 'BOV' },
          { value: 'BOP' },
          { value: 'BAM' },
          { value: 'BAD' },
          { value: 'BAN' },
          { value: 'BWP' },
          { value: 'BRC' },
          { value: 'BRZ' },
          { value: 'BRE' },
          { value: 'BRR' },
          { value: 'BRN' },
          { value: 'BRB' },
          { value: 'BRL' },
          { value: 'GBP' },
          { value: 'BND' },
          { value: 'BGL' },
          { value: 'BGN' },
          { value: 'BGO' },
          { value: 'BGM' },
          { value: 'BUK' },
          { value: 'BIF' },
          { value: 'XPF' },
          { value: 'KHR' },
          { value: 'CAD' },
          { value: 'CVE' },
          { value: 'KYD' },
          { value: 'XAF' },
          { value: 'CLE' },
          { value: 'CLP' },
          { value: 'CLF' },
          { value: 'CNX' },
          { value: 'CNY' },
          { value: 'CNH' },
          { value: 'COP' },
          { value: 'COU' },
          { value: 'KMF' },
          { value: 'CDF' },
          { value: 'CRC' },
          { value: 'HRD' },
          { value: 'HRK' },
          { value: 'CUC' },
          { value: 'CUP' },
          { value: 'CYP' },
          { value: 'CZK' },
          { value: 'CSK' },
          { value: 'DKK' },
          { value: 'DJF' },
          { value: 'DOP' },
          { value: 'NLG' },
          { value: 'XCD' },
          { value: 'DDM' },
          { value: 'ECS' },
          { value: 'ECV' },
          { value: 'EGP' },
          { value: 'GQE' },
          { value: 'ERN' },
          { value: 'EEK' },
          { value: 'ETB' },
          { value: 'EUR' },
          { value: 'XBA' },
          { value: 'XEU' },
          { value: 'XBB' },
          { value: 'XBC' },
          { value: 'XBD' },
          { value: 'FKP' },
          { value: 'FJD' },
          { value: 'FIM' },
          { value: 'FRF' },
          { value: 'XFO' },
          { value: 'XFU' },
          { value: 'GMD' },
          { value: 'GEK' },
          { value: 'GEL' },
          { value: 'DEM' },
          { value: 'GHS' },
          { value: 'GHC' },
          { value: 'GIP' },
          { value: 'XAU' },
          { value: 'GRD' },
          { value: 'GTQ' },
          { value: 'GWP' },
          { value: 'GNF' },
          { value: 'GNS' },
          { value: 'GYD' },
          { value: 'HTG' },
          { value: 'HNL' },
          { value: 'HKD' },
          { value: 'HUF' },
          { value: 'IMP' },
          { value: 'ISK' },
          { value: 'ISJ' },
          { value: 'INR' },
          { value: 'IDR' },
          { value: 'IRR' },
          { value: 'IQD' },
          { value: 'IEP' },
          { value: 'ILS' },
          { value: 'ILP' },
          { value: 'ILR' },
          { value: 'ITL' },
          { value: 'JMD' },
          { value: 'JPY' },
          { value: 'JOD' },
          { value: 'KZT' },
          { value: 'KES' },
          { value: 'KWD' },
          { value: 'KGS' },
          { value: 'LAK' },
          { value: 'LVL' },
          { value: 'LVR' },
          { value: 'LBP' },
          { value: 'LSL' },
          { value: 'LRD' },
          { value: 'LYD' },
          { value: 'LTL' },
          { value: 'LTT' },
          { value: 'LUL' },
          { value: 'LUC' },
          { value: 'LUF' },
          { value: 'MOP' },
          { value: 'MKD' },
          { value: 'MKN' },
          { value: 'MGA' },
          { value: 'MGF' },
          { value: 'MWK' },
          { value: 'MYR' },
          { value: 'MVR' },
          { value: 'MVP' },
          { value: 'MLF' },
          { value: 'MTL' },
          { value: 'MTP' },
          { value: 'MRU' },
          { value: 'MRO' },
          { value: 'MUR' },
          { value: 'MXV' },
          { value: 'MXN' },
          { value: 'MXP' },
          { value: 'MDC' },
          { value: 'MDL' },
          { value: 'MCF' },
          { value: 'MNT' },
          { value: 'MAD' },
          { value: 'MAF' },
          { value: 'MZE' },
          { value: 'MZN' },
          { value: 'MZM' },
          { value: 'MMK' },
          { value: 'NAD' },
          { value: 'NPR' },
          { value: 'ANG' },
          { value: 'TWD' },
          { value: 'NZD' },
          { value: 'NIO' },
          { value: 'NIC' },
          { value: 'NGN' },
          { value: 'KPW' },
          { value: 'NOK' },
          { value: 'OMR' },
          { value: 'PKR' },
          { value: 'XPD' },
          { value: 'PAB' },
          { value: 'PGK' },
          { value: 'PYG' },
          { value: 'PEI' },
          { value: 'PEN' },
          { value: 'PES' },
          { value: 'PHP' },
          { value: 'XPT' },
          { value: 'PLN' },
          { value: 'PLZ' },
          { value: 'PTE' },
          { value: 'GWE' },
          { value: 'QAR' },
          { value: 'XRE' },
          { value: 'RHD' },
          { value: 'RON' },
          { value: 'ROL' },
          { value: 'RUB' },
          { value: 'RUR' },
          { value: 'RWF' },
          { value: 'SVC' },
          { value: 'WST' },
          { value: 'SAR' },
          { value: 'RSD' },
          { value: 'CSD' },
          { value: 'SCR' },
          { value: 'SLL' },
          { value: 'XAG' },
          { value: 'SGD' },
          { value: 'SKK' },
          { value: 'SIT' },
          { value: 'SBD' },
          { value: 'SOS' },
          { value: 'ZAR' },
          { value: 'ZAL' },
          { value: 'KRH' },
          { value: 'KRW' },
          { value: 'KRO' },
          { value: 'SSP' },
          { value: 'SUR' },
          { value: 'ESP' },
          { value: 'ESA' },
          { value: 'ESB' },
          { value: 'XDR' },
          { value: 'LKR' },
          { value: 'SHP' },
          { value: 'XSU' },
          { value: 'SDD' },
          { value: 'SDG' },
          { value: 'SDP' },
          { value: 'SRD' },
          { value: 'SRG' },
          { value: 'SZL' },
          { value: 'SEK' },
          { value: 'CHF' },
          { value: 'SYP' },
          { value: 'STN' },
          { value: 'STD' },
          { value: 'TVD' },
          { value: 'TJR' },
          { value: 'TJS' },
          { value: 'TZS' },
          { value: 'XTS' },
          { value: 'THB' },
          { value: 'XXX' },
          { value: 'TPE' },
          { value: 'TOP' },
          { value: 'TTD' },
          { value: 'TND' },
          { value: 'TRY' },
          { value: 'TRL' },
          { value: 'TMT' },
          { value: 'TMM' },
          { value: 'USD' },
          { value: 'USN' },
          { value: 'USS' },
          { value: 'UGX' },
          { value: 'UGS' },
          { value: 'UAH' },
          { value: 'UAK' },
          { value: 'AED' },
          { value: 'UYW' },
          { value: 'UYU' },
          { value: 'UYP' },
          { value: 'UYI' },
          { value: 'UZS' },
          { value: 'VUV' },
          { value: 'VES' },
          { value: 'VEB' },
          { value: 'VEF' },
          { value: 'VND' },
          { value: 'VNN' },
          { value: 'CHE' },
          { value: 'CHW' },
          { value: 'XOF' },
          { value: 'YDD' },
          { value: 'YER' },
          { value: 'YUN' },
          { value: 'YUD' },
          { value: 'YUM' },
          { value: 'YUR' },
          { value: 'ZWN' },
          { value: 'ZRN' },
          { value: 'ZRZ' },
          { value: 'ZMW' },
          { value: 'ZMK' },
          { value: 'ZWD' },
          { value: 'ZWR' },
          { value: 'ZWL' },
        ],
      },
    },
    {
      key: 'company',
      label: 'Company',
      type: 'string',
    },
    {
      key: 'start_period',
      label: 'Start period',
      type: 'string',
    },
    {
      key: 'end_period',
      label: 'End period',
      type: 'string',
    },
    {
      key: 'cash_at_beginning_of_period',
      label: 'Cash at beginning of period',
      type: 'number',
    },
    {
      key: 'cash_at_end_of_period',
      label: 'Cash at end of period',
      type: 'number',
    },
    // operating_activities: ReportItem[]
    // investing_activities: ReportItem[]
    // financing_activities: ReportItem[]
    {
      key: 'remote_generated_at',
      label: 'Remote generated at',
      type: 'string',
    },
    {
      key: 'remote_was_deleted',
      label: 'Remote was deleted',
      type: 'boolean',
      constraints: [{ type: 'required' }],
    },
    {
      key: 'modified_at',
      label: 'Modified at',
      type: 'string',
      constraints: [{ type: 'required' }],
    },
    // field_mappings: Object
    // remote_data: RemoteData[]
  ],
  actions: [],
}
