name: Test
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  determine-packages:
    runs-on: ubuntu-latest
    outputs:
      packages: ${{ steps.set-packages.outputs.packages }}
    steps:
      - uses: actions/checkout@v4
      - name: Get package directories
        id: set-packages
        run: |
          # List of directories to search for packages
          SEARCH_DIRS="plugins utils validate convert enrich import export"
          
          # Find packages in all specified directories
          PACKAGES=$(
            for dir in $SEARCH_DIRS; do
              if [ -d "$dir" ]; then
                find "$dir" -maxdepth 1 -mindepth 1 -type d
              fi
            done | jq -R -s -c 'split("\n")[:-1]'
          )
          
          echo "packages=$PACKAGES" >> $GITHUB_OUTPUT
          echo "Found packages: $PACKAGES"

  test:
    needs: determine-packages
    name: Test
    timeout-minutes: 30
    runs-on: ubuntu-latest
    if: ${{ github.head_ref != 'changeset-release/main' }}
    strategy:
      matrix:
        package: ${{fromJson(needs.determine-packages.outputs.packages)}}
      fail-fast: false
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Test
        run: |
          PACKAGE_NAME=$(basename ${{ matrix.package }})
          npm run turbo:test --filter=$PACKAGE_NAME
