name: Test
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  determine-packages:
    runs-on: ubuntu-latest
    outputs:
      packages: ${{ steps.set-packages.outputs.packages }}
      unit_test_packages: ${{ steps.set-packages.outputs.unit_test_packages }}
      e2e_test_packages: ${{ steps.set-packages.outputs.e2e_test_packages }}
    steps:
      - uses: actions/checkout@v4
      - name: Get package names and test info
        id: set-packages
        run: |
          SEARCH_DIRS="plugins utils validate convert enrich import export"

          PACKAGES=()
          UNIT_TEST_PACKAGES=()
          E2E_TEST_PACKAGES=()

          for dir in $SEARCH_DIRS; do
            if [ -d "$dir" ]; then
              while IFS= read -r package_json; do
                PACKAGE_DIR=$(dirname "$package_json")
                PACKAGE_NAME=$(jq -r .name "$package_json")
                if [ "$PACKAGE_NAME" != "null" ]; then
                  PACKAGES+=("$PACKAGE_NAME")
                  
                  if [ -n "$(find "$PACKAGE_DIR" -name "*.spec.ts" -not -name "*.e2e.spec.ts")" ]; then
                    UNIT_TEST_PACKAGES+=("$PACKAGE_NAME")
                  fi
                  
                  if [ -n "$(find "$PACKAGE_DIR" -name "*.e2e.spec.ts")" ]; then
                    E2E_TEST_PACKAGES+=("$PACKAGE_NAME")
                  fi
                fi
              done < <(find "$dir" -maxdepth 2 -name "package.json")
            fi
          done

          echo "packages=$(jq -nc '$ARGS.positional' --args "${PACKAGES[@]}")" >> $GITHUB_OUTPUT
          echo "unit_test_packages=$(jq -nc '$ARGS.positional' --args "${UNIT_TEST_PACKAGES[@]}")" >> $GITHUB_OUTPUT
          echo "e2e_test_packages=$(jq -nc '$ARGS.positional' --args "${E2E_TEST_PACKAGES[@]}")" >> $GITHUB_OUTPUT
          
          echo "Found packages: ${PACKAGES[*]}"
          echo "Packages with unit tests: ${UNIT_TEST_PACKAGES[*]}"
          echo "Packages with E2E tests: ${E2E_TEST_PACKAGES[*]}"

  setup:
    needs: determine-packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npx turbo run build

  unit-tests:
    needs: setup
    name: Unit Tests (${{ matrix.package }})
    runs-on: ubuntu-latest
    if: ${{ github.head_ref != 'changeset-release/main' }}
    strategy:
      matrix:
        package: ${{fromJson(needs.determine-packages.outputs.unit_test_packages)}}
      fail-fast: false
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run unit tests
        run: npx turbo run test:unit --filter=${{ matrix.package }}

  e2e-tests:
    needs: setup
    name: E2E Tests
    runs-on: ubuntu-latest
    if: ${{ github.head_ref != 'changeset-release/main' }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run E2E tests
        run: |
          for package in ${{join(fromJson(needs.determine-packages.outputs.e2e_test_packages), ' ')}}; do
            echo "Running E2E tests for $package"
            npx turbo run test:e2e --filter=$package
          done

  test:
    needs: [unit-tests, e2e-tests]
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Check test results
        run: |
          echo "All unit and E2E tests completed successfully"
          exit 0
